### PR TITLE
Remove APT cache from CompreFace

### PR DESCRIPTION
**Pull request by felipecrs**

### CODE REVIEW

**Comment by jakowenko** [comment]
Thank you for this. Is it worth running any of the other clean commands to reduce the size?

`apt-get clean` or `apt-get autoclean`?

**Comment by felipecrs** [comment]
No, `rm -rf /var/lib/apt/lists/*` takes care of everything. [Reference](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#:~:text=In%20addition%2C%20when%20you%20clean%20up%20the%20apt%20cache%20by%20removing%20/var/lib/apt/lists%20it%20reduces%20the%20image%20size%2C%20since%20the%20apt%20cache%20is%20not%20stored%20in%20a%20layer.%20Since%20the%20RUN%20statement%20starts%20with%20apt%2Dget%20update%2C%20the%20package%20cache%20is%20always%20refreshed%20prior%20to%20apt%2Dget%20install.).

**Comment by jakowenko** [comment]
@felipecrs I noticed you removed `RUN rm /etc/postgresql/13/main/postgresql.conf` too. Was this intentional? Maybe it's not needed since the next command copies it over.

I'm getting this addon ready for CompreFace 1.0.0, so I will fix if it was by mistake.

**Comment by felipecrs** [comment]
@jakowenko yes, that's unnecessary. `COPY` will automatically overwrite the file if it already exists.

**Pull request merged**
